[tools]
typst = 'latest'
bun = 'latest'
uv = 'latest'
"github:Slackadays/Clipboard" = "latest"

[tasks.compile]
description = 'Compile all Typst files in the homeworks directory to PDFs.'
run = '''
#!/usr/bin/env bun

import { $ } from "bun";
for await (let file of $`ls *.typ`.lines()) {
  file.trim() && await $`typst compile ${file} ${file.replace('.typ', '.pdf')} --root ..`;
}
'''
dir = "homeworks"

[tasks.compute]
description = 'Run copied Python script.'
run = [
  "cb paste | uv run -"
]
